In [ ]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras_tuner.tuners import RandomSearch

# Load and prepare the data
data = pd.read_csv('Данные объявлений об эскорт-услугах в Москве(214k).csv')
data['DateUpdate'] = pd.to_datetime(data['DateUpdate'], format='%d.%m.%Y')
clean_data = data.dropna()

# Select relevant features for prediction
features = ['Age', 'Boobs', 'Height', 'Size', 'Weight']
X = clean_data[features]
y = clean_data['Price_USD']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define a model-building function with added regularization
def build_model(hp):
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Dense(
        units=hp.Int('units_1', min_value=32, max_value=512, step=32),
        activation='relu',
        input_shape=(X_train_scaled.shape[1],),
        kernel_regularizer=tf.keras.regularizers.l2(0.01)
    ))
    model.add(tf.keras.layers.Dropout(0.5))
    model.add(tf.keras.layers.Dense(
        units=hp.Int('units_2', min_value=32, max_value=512, step=32),
        activation='relu',
        kernel_regularizer=tf.keras.regularizers.l2(0.01)
    ))
    model.add(tf.keras.layers.Dropout(0.5))
    model.add(tf.keras.layers.Dense(
        units=hp.Int('units_3', min_value=16, max_value=256, step=16),
        activation='relu',
        kernel_regularizer=tf.keras.regularizers.l2(0.01)
    ))
    model.add(tf.keras.layers.Dense(1))

    model.compile(
        optimizer=tf.keras.optimizers.Adam(
            hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])),
        loss='mean_squared_error'
    )
    return model

# Initialize the Keras Tuner
tuner = RandomSearch(
    build_model,
    objective='val_loss',
    max_trials=5,
    executions_per_trial=3,
    directory='my_dir',
    project_name='helloworld'
)

# Implement Early Stopping
early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

# Perform hypertuning
tuner.search(X_train_scaled, y_train, epochs=100, validation_split=0.2, callbacks=[early_stopping])

# Get the best model
best_model = tuner.get_best_models(num_models=1)[0]

# Evaluate the model on the test set
loss = best_model.evaluate(X_test_scaled, y_test)
print(f"Test Loss: {loss}")

# Function to predict new data
def predict_new_data(model, scaler, new_data):
    """
    Predicts the price for new data.

    Parameters:
    model (tf.keras.Model): The trained model.
    scaler (StandardScaler): The fitted scaler.
    new_data (pd.DataFrame): The new data for prediction.

    Returns:
    float: The predicted price.
    """
    # Scale the new data
    new_data_scaled = scaler.transform(new_data)

    # Predict using the trained model
    prediction = model.predict(new_data_scaled)

    return prediction

# Example new data for prediction
new_data = pd.DataFrame({
    'Age': [25],
    'Boobs': [3],
    'Height': [170],
    'Size': [44],
    'Weight': [55]
})

# Predict the price for the new data
predicted_price = predict_new_data(best_model, scaler, new_data)
print(f"Predicted Price: {predicted_price[0][0]}")



Search: Running Trial #1

Value             |Best Value So Far |Hyperparameter
96                |96                |units_1
224               |224               |units_2
176               |176               |units_3
0.01              |0.01              |learning_rate

Epoch 1/100
3775/3775 [==============================] - 21s 5ms/step - loss: 2491.7605 - val_loss: 2562.6758
Epoch 2/100
3775/3775 [==============================] - 19s 5ms/step - loss: 2463.0107 - val_loss: 2550.9487
Epoch 3/100
3775/3775 [==============================] - 19s 5ms/step - loss: 2447.7878 - val_loss: 2596.0959
Epoch 4/100
3775/3775 [==============================] - 20s 5ms/step - loss: 2439.3123 - val_loss: 2557.5168
Epoch 5/100
3775/3775 [==============================] - 23s 6ms/step - loss: 2427.1406 - val_loss: 2625.7659
Epoch 6/100
3775/3775 [==============================] - 21s 6ms/step - loss: 2425.0532 - val_loss: 2598.5039
Epoch 7/100
3775/3775 [==============================] - 20s 5ms/step

KeyboardInterrupt: 

In [ ]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras_tuner.tuners import RandomSearch

# Load and prepare the data
data = pd.read_csv('Данные объявлений об эскорт-услугах в Москве(214k).csv')
data['DateUpdate'] = pd.to_datetime(data['DateUpdate'], format='%d.%m.%Y')
clean_data = data.dropna()

# Select relevant features for prediction
features = ['Age', 'Boobs', 'Height', 'Size', 'Weight']
X = clean_data[features]
y = clean_data['Price_USD']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define a model-building function with multiple improvements
def build_model(hp):
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Dense(
        units=hp.Int('units_1', min_value=32, max_value=512, step=32),
        activation='relu',
        input_shape=(X_train_scaled.shape[1],),
        kernel_regularizer=tf.keras.regularizers.l2(0.01)
    ))
    model.add(tf.keras.layers.BatchNormalization())
    model.add(tf.keras.layers.Dropout(0.5))
    model.add(tf.keras.layers.Dense(
        units=hp.Int('units_2', min_value=32, max_value=512, step=32),
        activation='relu',
        kernel_regularizer=tf.keras.regularizers.l2(0.01)
    ))
    model.add(tf.keras.layers.BatchNormalization())
    model.add(tf.keras.layers.Dropout(0.5))
    model.add(tf.keras.layers.Dense(
        units=hp.Int('units_3', min_value=16, max_value=256, step=16),
        activation='relu',
        kernel_regularizer=tf.keras.regularizers.l2(0.01)
    ))
    model.add(tf.keras.layers.Dense(1))

    model.compile(
        optimizer=tf.keras.optimizers.Adam(
            hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])),
        loss='mean_squared_error'
    )
    return model

# Initialize the Keras Tuner
tuner = RandomSearch(
    build_model,
    objective='val_loss',
    max_trials=5,
    executions_per_trial=3,
    directory='my_dir',
    project_name='helloworld'
)

# Implement custom early stopping
class CustomEarlyStopping(tf.keras.callbacks.Callback):
    def __init__(self, patience=10, threshold=30):
        super(CustomEarlyStopping, self).__init__()
        self.patience = patience
        self.threshold = threshold
        self.best_weights = None

    def on_train_begin(self, logs=None):
        self.wait = 0
        self.stopped_epoch = 0
        self.best = float('inf')
        self.loss_history = []

    def on_epoch_end(self, epoch, logs=None):
        current_loss = logs.get('loss')
        current_val_loss = logs.get('val_loss')

        self.loss_history.append((current_loss, current_val_loss))

        if epoch >= self.patience:
            recent_losses = self.loss_history[-self.patience:]
            if all(abs(recent_losses[i][0] - recent_losses[i-1][0]) < self.threshold and
                   abs(recent_losses[i][1] - recent_losses[i-1][1]) < self.threshold for i in range(1, self.patience)):
                self.model.stop_training = True
                self.stopped_epoch = epoch
                print(f"Early stopping triggered at epoch {epoch+1}")

# Perform hypertuning with custom early stopping and learning rate reduction
custom_early_stopping = CustomEarlyStopping(patience=10, threshold=30)
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=0.0001)

tuner.search(X_train_scaled, y_train, epochs=100, validation_split=0.2, callbacks=[custom_early_stopping, reduce_lr])

# Get the best model
best_model = tuner.get_best_models(num_models=1)[0]

# Evaluate the model on the test set
loss = best_model.evaluate(X_test_scaled, y_test)
print(f"Test Loss: {loss}")

# Function to predict new data
def predict_new_data(model, scaler, new_data):
    """
    Predicts the price for new data.

    Parameters:
    model (tf.keras.Model): The trained model.
    scaler (StandardScaler): The fitted scaler.
    new_data (pd.DataFrame): The new data for prediction.

    Returns:
    float: The predicted price.
    """
    # Scale the new data
    new_data_scaled = scaler.transform(new_data)

    # Predict using the trained model
    prediction = model.predict(new_data_scaled)

    return prediction

# Example new data for prediction
new_data = pd.DataFrame({
    'Age': [25],
    'Boobs': [3],
    'Height': [170],
    'Size': [44],
    'Weight': [55]
})

# Predict the price for the new data
predicted_price = predict_new_data(best_model, scaler, new_data)
print(f"Predicted Price: {predicted_price[0][0]}")



Search: Running Trial #1

Value             |Best Value So Far |Hyperparameter
64                |64                |units_1
192               |192               |units_2
256               |256               |units_3
0.01              |0.01              |learning_rate

Epoch 1/100
3775/3775 [==============================] - 28s 7ms/step - loss: 2501.4170 - val_loss: 2574.8306 - lr: 0.0100
Epoch 2/100
2699/3775 [====================>.........] - ETA: 6s - loss: 2473.4741

KeyboardInterrupt: 

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import TensorBoard, LambdaCallback
import datetime

# Load the data
data = pd.read_csv('Данные объявлений об эскорт-услугах в Москве(214k).csv')
data['DateUpdate'] = pd.to_datetime(data['DateUpdate'], format='%d.%m.%Y')
data.sort_values('DateUpdate', inplace=True)

# Ensure the data is clean
clean_data = data.dropna()

# Select relevant features for prediction
features = ['Age', 'Boobs', 'Height', 'Size', 'Weight']
target = 'Price_USD'
clean_data = clean_data[features + [target]]

# Separate features and target
X = clean_data[features]
y = clean_data[target]

# Standardize the features
feature_scaler = StandardScaler()
X_scaled = feature_scaler.fit_transform(X)

# Standardize the target
target_scaler = StandardScaler()
y_scaled = target_scaler.fit_transform(y.values.reshape(-1, 1))

# Convert to time series format
def create_time_series(X_data, y_data, n_steps):
    X, y = [], []
    for i in range(len(X_data) - n_steps):
        X.append(X_data[i:i + n_steps])
        y.append(y_data[i + n_steps])
    return np.array(X), np.array(y)

n_steps = 10
X_ts, y_ts = create_time_series(X_scaled, y_scaled, n_steps)

# Split the data into training and testing sets
split_ratio = 0.8
split = int(len(X_ts) * split_ratio)
X_train, X_test = X_ts[:split], X_ts[split:]
y_train, y_test = y_ts[:split], y_ts[split:]

# Define the model
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train.shape[1], X_train.shape[2])),
    tf.keras.layers.LSTM(128, activation='relu', return_sequences=True),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.LSTM(64, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1)
])

# Compile the model
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mean_squared_error')

# Custom callback for early stopping
class CustomEarlyStopping(tf.keras.callbacks.Callback):
    def __init__(self, patience=10, threshold=30):
        super(CustomEarlyStopping, self).__init__()
        self.patience = patience
        self.threshold = threshold
        self.best_weights = None

    def on_train_begin(self, logs=None):
        self.wait = 0
        self.stopped_epoch = 0
        self.best = float('inf')
        self.loss_history = []

    def on_epoch_end(self, epoch, logs=None):
        current_loss = logs.get('loss')
        current_val_loss = logs.get('val_loss')

        self.loss_history.append((current_loss, current_val_loss))

        if epoch >= self.patience:
            recent_losses = self.loss_history[-self.patience:]
            if all(abs(recent_losses[i][0] - recent_losses[i-1][0]) < self.threshold and
                   abs(recent_losses[i][1] - recent_losses[i-1][1]) < self.threshold for i in range(1, self.patience)):
                self.model.stop_training = True
                self.stopped_epoch = epoch
                print(f"Early stopping triggered at epoch {epoch+1}")

# TensorBoard callback
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

# Lambda callback to print loss and val_loss at each epoch
print_callback = LambdaCallback(
    on_epoch_end=lambda epoch, logs: print(f"Epoch {epoch+1}: loss = {logs['loss']}, val_loss = {logs['val_loss']}")
)

# Perform training with custom early stopping and learning rate reduction
custom_early_stopping = CustomEarlyStopping(patience=10, threshold=30)
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=0.0001)

# Train the model for 1 epoch
history = model.fit(X_train, y_train, epochs=1, validation_split=0.2, callbacks=[custom_early_stopping, reduce_lr, tensorboard_callback, print_callback])

# Evaluate the model on the test set
loss = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss}")

# Function to predict new data
def predict_new_data(model, feature_scaler, target_scaler, new_data, n_steps):
    """
    Predicts the price for new data.

    Parameters:
    model (tf.keras.Model): The trained model.
    feature_scaler (StandardScaler): The scaler fitted on the features.
    target_scaler (StandardScaler): The scaler fitted on the target.
    new_data (pd.DataFrame): The new data for prediction.
    n_steps (int): Number of time steps to look back.

    Returns:
    np.array: The predicted prices.
    """
    if len(new_data) < n_steps:
        raise ValueError(f"New data must have at least {n_steps} rows.")

    scaled_new_data = feature_scaler.transform(new_data)
    print(f"Scaled new data: {scaled_new_data}")  # Debug information
    X_new = []
    for i in range(len(scaled_new_data) - n_steps + 1):
        X_new.append(scaled_new_data[i:i + n_steps])
    X_new = np.array(X_new)
    if len(X_new) == 0:
        raise ValueError("Expected input data to be non-empty after processing.")
    predictions = model.predict(X_new)
    predictions_rescaled = target_scaler.inverse_transform(predictions)
    return predictions_rescaled

# Example new data for prediction without 'Price_USD'
new_data = pd.DataFrame({
    'Age': [25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
    'Boobs': [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
    'Height': [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
    'Size': [44, 44, 44, 44, 44, 44, 44, 44, 44, 44],
    'Weight': [55, 56, 57, 58, 59, 60, 61, 62, 63, 64]
})

# Print the shape of new data for debugging
print(f"New data shape: {new_data.shape}")

# Predict the price for the new data
predicted_prices = predict_new_data(model, feature_scaler, target_scaler, new_data, n_steps)
print(f"Predicted Prices: {predicted_prices}")


1180/1180 [==============================] - 12s 10ms/step - loss: 1.7195
Test Loss: 1.7195430994033813
New data shape: (10, 5)
Scaled new data: [[-0.28612874  0.26893377  0.18268486 -0.03122472 -0.17694565]
 [-0.13528393  0.26893377  0.38390626 -0.03122472 -0.05749265]
 [ 0.01556089  0.26893377  0.58512767 -0.03122472  0.06196035]
 [ 0.16640571  0.26893377  0.78634908 -0.03122472  0.18141335]
 [ 0.31725053  0.26893377  0.98757049 -0.03122472  0.30086635]
 [ 0.46809535  0.26893377  1.1887919  -0.03122472  0.42031935]
 [ 0.61894017  0.26893377  1.39001331 -0.03122472  0.53977235]
 [ 0.76978498  0.26893377  1.59123472 -0.03122472  0.65922535]
 [ 0.9206298   0.26893377  1.79245613 -0.03122472  0.77867835]
 [ 1.07147462  0.26893377  1.99367753 -0.03122472  0.89813135]]
1/1 [==============================] - 0s 333ms/step
Predicted Prices: [[44.24057]]


In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import joblib
import os
from google.colab import files

# Load the data
data = pd.read_csv('Данные объявлений об эскорт-услугах в Москве(214k).csv')
data['DateUpdate'] = pd.to_datetime(data['DateUpdate'], format='%d.%m.%Y')
data.sort_values('DateUpdate', inplace=True)

# Ensure the data is clean
clean_data = data.dropna()

# Select relevant features for prediction
features = ['Age', 'Boobs', 'Height', 'Size', 'Weight']
target = 'Price_USD'
clean_data = clean_data[features + [target]]

# Separate features and target
X = clean_data[features]
y = clean_data[target]

# Standardize the features
feature_scaler = StandardScaler()
X_scaled = feature_scaler.fit_transform(X)

# Standardize the target
target_scaler = StandardScaler()
y_scaled = target_scaler.fit_transform(y.values.reshape(-1, 1))

# Convert to time series format
def create_time_series(X_data, y_data, n_steps):
    X, y = [], []
    for i in range(len(X_data) - n_steps):
        X.append(X_data[i:i + n_steps])
        y.append(y_data[i + n_steps])
    return np.array(X), np.array(y)

n_steps = 10
X_ts, y_ts = create_time_series(X_scaled, y_scaled, n_steps)

# Split the data into training and testing sets
split_ratio = 0.8
split = int(len(X_ts) * split_ratio)
X_train, X_test = X_ts[:split], X_ts[split:]
y_train, y_test = y_ts[:split], y_ts[split:]

# Define the model
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train.shape[1], X_train.shape[2])),
    tf.keras.layers.LSTM(128, activation='relu', return_sequences=True),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.LSTM(64, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1)
])

# Compile the model
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mean_squared_error')

# Train the model for 1 epoch (for demonstration purposes)
history = model.fit(X_train, y_train, epochs=1, validation_split=0.2)

# Create directory to save the files
save_dir = 'saved_models'
os.makedirs(save_dir, exist_ok=True)

# Save the model
model_path = os.path.join(save_dir, 'lstm_model.h5')
model.save(model_path)

# Save the scalers
feature_scaler_path = os.path.join(save_dir, 'feature_scaler.pkl')
target_scaler_path = os.path.join(save_dir, 'target_scaler.pkl')
joblib.dump(feature_scaler, feature_scaler_path)
joblib.dump(target_scaler, target_scaler_path)

# Download the model and scalers
files.download(model_path)
files.download(feature_scaler_path)
files.download(target_scaler_path)

# Function to predict new data
def predict_price(age, boobs, height, size, weight, model, feature_scaler, target_scaler, n_steps):
    # Create a DataFrame with the input data
    new_data = pd.DataFrame({
        'Age': [age] * n_steps,
        'Boobs': [boobs] * n_steps,
        'Height': [height] * n_steps,
        'Size': [size] * n_steps,
        'Weight': [weight] * n_steps
    })

    # Scale the input data
    scaled_new_data = feature_scaler.transform(new_data)

    # Prepare the time window for prediction
    X_new = np.array([scaled_new_data])

    # Make the prediction
    prediction = model.predict(X_new)

    # Inverse transform the prediction
    predicted_price = target_scaler.inverse_transform(prediction)
    return predicted_price[0][0]

# Example of using the prediction function
age = 25
boobs = 3
height = 170
size = 44
weight = 55

predicted_price = predict_price(age, boobs, height, size, weight, model, feature_scaler, target_scaler, n_steps)
print(f"Predicted Price: {predicted_price}")

3774/3774 [==============================] - 99s 25ms/step - loss: 0.7528 - val_loss: 1.2144


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

1/1 [==============================] - 0s 290ms/step
Predicted Price: 45.8592529296875


In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
import joblib

# Load the saved model and scalers
model = tf.keras.models.load_model('lstm_model.h5')
feature_scaler = joblib.load('feature_scaler.pkl')
target_scaler = joblib.load('target_scaler.pkl')

# Function to predict new data
def predict_price(age, boobs, height, size, weight, model, feature_scaler, target_scaler, n_steps):
    # Create a DataFrame with the input data
    new_data = pd.DataFrame({
        'Age': [age] * n_steps,
        'Boobs': [boobs] * n_steps,
        'Height': [height] * n_steps,
        'Size': [size] * n_steps,
        'Weight': [weight] * n_steps
    })

    # Scale the input data
    scaled_new_data = feature_scaler.transform(new_data)

    # Prepare the time window for prediction
    X_new = np.array([scaled_new_data])

    # Make the prediction
    prediction = model.predict(X_new)

    # Inverse transform the prediction
    predicted_price = target_scaler.inverse_transform(prediction)
    return predicted_price[0][0]

# Example of using the prediction function
age = 21
boobs = 2
height = 180
size = 44
weight = 60

predicted_price = predict_price(age, boobs, height, size, weight, model, feature_scaler, target_scaler, n_steps)
print(f"Predicted Price: {predicted_price}")


1/1 [==============================] - 1s 673ms/step
Predicted Price: 44.222381591796875
